force-app/main/default/objects/Distribution_Center__c/Distribution_Center__c.object-meta.xml
<CustomObject>
    <description>To allow Probably On-Time Deliveries to better manage all of their distribution centers.</description>
    <label>Distribution Center</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Center__c/fields/Current_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Current_Number_of_Vehicles__c</fullName>
    <label>Current Number of Vehicles</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distribution_Center__c/fields/States_Covered__c.field-meta.xml
<CustomField>
    <fullName>States_Covered__c</fullName>
    <label>States Covered</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IIA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Distribution_Center__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origin Location</label>
    <referenceTo>Distribution_Center__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Last_Departure__c.field-meta.xml
<CustomField>
    <fullName>Last_Departure__c</fullName>
    <label>Last Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Schedule__c/Vehicle_Schedule__c.object-meta.xml
<CustomObject>
    <label>Vehicle Schedule</label>
    <nameField>
        <label>Vehicle Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles Scedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Schedule__c/fields/Distribution_Center__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Center__c</fullName>
    <label>Distribution Center</label>
    <referenceTo>Distribution_Center__c</referenceTo>
    <relationshipLabel>Vehicles Schedule</relationshipLabel>
    <relationshipName>Vehicles_Schedule</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Schedule__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Vehicles Schedule</relationshipLabel>
    <relationshipName>Vehicles_Scedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ExampleSOQL.cls
public class ExampleSOQL {
    public static void ExampleSOQLQueries(){
        List<Distribution_Center__c> distributionCenters = [SELECT Name, Current_Number_of_Vehicles__c, States_Covered__c FROM Distribution_Center__c WHERE Current_Number_of_Vehicles__c>5];
        for(Distribution_Center__c dc : distributionCenters){
            System.debug(dc.Name + ' has ' + dc.Current_Number_of_Vehicles__c + ' vehicles.');
        }
        //List<Vehicle_Schedule__c> vehicleSchedules = [SELECT Vehicle__r.Number_of_Packages__c, Distribution_Center__r.Name FROM Vehicle_Schedule__c];
        //system.debug(vehicleSchedules);
        List<AggregateResult> centerPackages = [SELECT sum(Vehicle__r.Number_of_Packages__c)totalPackages, Distribution_Center__r.Name FROM Vehicle_Schedule__c GROUP BY Distribution_Center__r.Name];
        for(AggregateResult cp : centerPackages){
            system.debug(cp.get('Name') + ' has ' + cp.get('totalPackages') + ' packages.');
        }
        try{
        	Vehicle__c vehicle = [SELECT Number_of_Packages__c, Last_Departure__c FROM Vehicle__c WHERE Last_Departure__c = LAST_MONTH LIMIT 1];
        }catch(System.QueryException qe){
            system.debug(qe.getMessage());
        }
    }

}