force-app/main/default/objects/Distribution_Center__c/Distribution_Center__c.object-meta.xml
<CustomObject>
    <description>To allow Probably On-Time Deliveries to better manage all of their distribution centers.</description>
    <label>Distribution Center</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Center__c/fields/Current_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Current_Number_of_Vehicles__c</fullName>
    <label>Current Number of Vehicles</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distribution_Center__c/fields/Max_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Max_Number_of_Vehicles__c</fullName>
    <label>Max Number of Vehicles</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distribution_Center__c/fields/States_Covered__c.field-meta.xml
<CustomField>
    <fullName>States_Covered__c</fullName>
    <label>States Covered</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IIA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Distribution_Center__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Distribution_Center__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origin Location</label>
    <referenceTo>Distribution_Center__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Last_Departure__c.field-meta.xml
<CustomField>
    <fullName>Last_Departure__c</fullName>
    <label>Last Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Schedule__c/Vehicle_Schedule__c.object-meta.xml
<CustomObject>
    <label>Vehicle Schedule</label>
    <nameField>
        <label>Vehicle Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles Scedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Schedule__c/fields/Distribution_Center__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Center__c</fullName>
    <label>Distribution Center</label>
    <referenceTo>Distribution_Center__c</referenceTo>
    <relationshipLabel>Vehicles Schedule</relationshipLabel>
    <relationshipName>Vehicles_Schedule</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Schedule__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Vehicles Schedule</relationshipLabel>
    <relationshipName>Vehicles_Scedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SOQLDataFactory.cls
public class SOQLDataFactory {
    public static void createData(){
        List<Distribution_Center__c> dcList = new List<Distribution_Center__c>();
        dcList.add(new Distribution_Center__c(Name='Atlanta Distribution Center', Current_Number_of_Vehicles__c=10, 
                                              Max_Number_of_Vehicles__c=20, City__c='Atlanta', State__c='GA', 
                                              States_Covered__c='AL;GA', Street__c='2955 Cobb Pkwy SE', 
                                              Zip_Code__c='30339'));
        dcList.add(new Distribution_Center__c(Name='Buffalo Distribution Center', Current_Number_of_Vehicles__c=5, 
                                              Max_Number_of_Vehicles__c=15, City__c='Buffalo', State__c='NY', 
                                              States_Covered__c='NY;PA', Street__c='2141 Elmwood Ave', 
                                              Zip_Code__c='14207'));
        dcList.add(new Distribution_Center__c(Name='Champlain Distribution Center', Current_Number_of_Vehicles__c=3, 
                                              Max_Number_of_Vehicles__c=15, City__c='Champlain', State__c='NY', 
                                              States_Covered__c='NY;VT', Street__c='215 Dorset St', 
                                              Zip_Code__c='05403'));
        dcList.add(new Distribution_Center__c(Name='Chicago Distribution Center', Current_Number_of_Vehicles__c=10, 
                                              Max_Number_of_Vehicles__c=25, City__c='Chicago', State__c='IL', 
                                              States_Covered__c='IL;IN;WI', Street__c='1514 W 33rd St', 
                                              Zip_Code__c='60608'));
        dcList.add(new Distribution_Center__c(Name='Detroit Distribution Center', Current_Number_of_Vehicles__c=5, 
                                              Max_Number_of_Vehicles__c=20, City__c='Detroit', State__c='MI', 
                                              States_Covered__c='MI;OH', Street__c='29800 Southfield Rd', 
                                              Zip_Code__c='48127'));
        dcList.add(new Distribution_Center__c(Name='El Paso Distribution Center', Current_Number_of_Vehicles__c=3, 
                                              Max_Number_of_Vehicles__c=15, City__c='El Paso', State__c='TX', 
                                              States_Covered__c='NM;TX', Street__c='1842 Joe Battle Blvd', 
                                              Zip_Code__c='79936'));
        dcList.add(new Distribution_Center__c(Name='Laredo Distribution Center', Current_Number_of_Vehicles__c=3, 
                                              Max_Number_of_Vehicles__c=15, City__c='Laredo', State__c='TX', 
                                              States_Covered__c='TX', Street__c='7607 San Dario Ave', 
                                              Zip_Code__c='78045'));
        dcList.add(new Distribution_Center__c(Name='Los Angeles Distribution Center', Current_Number_of_Vehicles__c=10, 
                                              Max_Number_of_Vehicles__c=25, City__c='Los Angeles', State__c='CA', 
                                              States_Covered__c='CA', Street__c='2935 Los Feliz Blvd', 
                                              Zip_Code__c='90039'));
        dcList.add(new Distribution_Center__c(Name='San Diego Distribution Center', Current_Number_of_Vehicles__c=3, 
                                              Max_Number_of_Vehicles__c=20, City__c='San Diego', State__c='CA', 
                                              States_Covered__c='CA', Street__c='4251 Genesee Ave', 
                                              Zip_Code__c='92117'));
        dcList.add(new Distribution_Center__c(Name='Seattle Distribution Center', Current_Number_of_Vehicles__c=3, 
                                              Max_Number_of_Vehicles__c=20, City__c='Seattle', State__c='WA', 
                                              States_Covered__c='WA', Street__c='15600 NE 8th St', 
                                              Zip_Code__c='98101'));
        insert dcList;
        
        List<Vehicle__c> vList = new List<Vehicle__c>();
        Integer numPackages = 0;
        Date departDate;
        for(Integer i = 0; i < 55; i++){
            numPackages = Integer.valueOf(Math.floor(Math.random() * 20));
            departDate = Date.today().addDays(-Integer.valueOf(Math.ceil(Math.random() * 7)));
            vList.add(new Vehicle__c(Name='VAN-000' + i, Last_Departure__c=departDate, 
                                     Number_of_Packages__c=numPackages));
        }
        insert vList;
        
        List<Vehicle_Schedule__c> vsList = new List<Vehicle_Schedule__c>();
        for(Integer i = 0; i < 55; i++){
            if(i < 10){
                vsList.add(new Vehicle_Schedule__c(Name='VS-000' + i, Distribution_Center__c=dcList[0].Id, 
                                                   Vehicle__c=vList[i].Id));
            }
            else if(i < 15){
                vsList.add(new Vehicle_Schedule__c(Name='VS-000' + i, Distribution_Center__c=dcList[1].Id, 
                                                   Vehicle__c=vList[i].Id));
            }
            else if(i < 18){
                vsList.add(new Vehicle_Schedule__c(Name='VS-000' + i, Distribution_Center__c=dcList[2].Id, 
                                                   Vehicle__c=vList[i].Id));
            }
            else if(i < 28){
                vsList.add(new Vehicle_Schedule__c(Name='VS-000' + i, Distribution_Center__c=dcList[3].Id, 
                                                   Vehicle__c=vList[i].Id));
            }
            else if(i < 33){
                vsList.add(new Vehicle_Schedule__c(Name='VS-000' + i, Distribution_Center__c=dcList[4].Id, 
                                                   Vehicle__c=vList[i].Id));
            }
            else if(i < 36){
                vsList.add(new Vehicle_Schedule__c(Name='VS-000' + i, Distribution_Center__c=dcList[5].Id, 
                                                   Vehicle__c=vList[i].Id));
            }
            else if(i < 39){
                vsList.add(new Vehicle_Schedule__c(Name='VS-000' + i, Distribution_Center__c=dcList[6].Id, 
                                                   Vehicle__c=vList[i].Id));
            }
            else if(i < 49){
                vsList.add(new Vehicle_Schedule__c(Name='VS-000' + i, Distribution_Center__c=dcList[7].Id, 
                                                   Vehicle__c=vList[i].Id));
            }
            else if(i < 52){
                vsList.add(new Vehicle_Schedule__c(Name='VS-000' + i, Distribution_Center__c=dcList[8].Id, 
                                                   Vehicle__c=vList[i].Id));
            }
            else{
                vsList.add(new Vehicle_Schedule__c(Name='VS-000' + i, Distribution_Center__c=dcList[9].Id, 
                                                   Vehicle__c=vList[i].Id));
            }
        }
        insert vsList;
    }
}