force-app/main/default/objects/Distribution_Center__c/Distribution_Center__c.object-meta.xml
<CustomObject>
    <description>To allow Probably On-Time Deliveries to better manage all of their distribution centers.</description>
    <label>Distribution Center</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Distribution_Center__c/fields/Max_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Max_Number_of_Vehicles__c</fullName>
    <label>Max Number of Vehicles</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distribution_Center__c/fields/States_Covered__c.field-meta.xml
<CustomField>
    <fullName>States_Covered__c</fullName>
    <label>States Covered</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IIA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>TN</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Distribution_Center__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Distribution_Center__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origin Location</label>
    <referenceTo>Distribution_Center__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Schedule__c/Vehicle_Schedule__c.object-meta.xml
<CustomObject>
    <label>Vehicle Schedule</label>
    <nameField>
        <label>Vehicle Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles Scedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Schedule__c/fields/Distribution_Center__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Center__c</fullName>
    <label>Distribution Center</label>
    <referenceTo>Distribution_Center__c</referenceTo>
    <relationshipLabel>Vehicles Schedule</relationshipLabel>
    <relationshipName>Vehicles_Schedule</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Schedule__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Vehicles Schedule</relationshipLabel>
    <relationshipName>Vehicles_Scedule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ExampleDML.cls
public class ExampleDML {
    
    public static void ExampleDMLInsert(){
        
        Vehicle__c memphisVan = new Vehicle__c();
        
        List<Database.SaveResult> Isr = new List<Database.SaveResult>();
        
        Distribution_Center__c memphisCenter = new Distribution_Center__c(
        	Name = 'Memphis Distribution Center',
        	City__c = 'Memphis',
        	Max_Number_of_Vehicles__c = 25,
        	State__c = 'TN',
        	States_Covered__c = 'AR;MS;TN',
        	Street__c = '3460 Poplar Ave',
        	Zip_Code__c ='38111');
        
        Distribution_Center__c dallasCenter = new Distribution_Center__c(
        	Name = 'Dallas Distribution Center',
        	City__c = 'Dallas',
        	Max_Number_of_Vehicles__c = 20,
        	State__c = 'TX',
        	States_Covered__c = 'OK;TX',
        	Street__c = '39579 Lyndon B Johnson Freeway',
        	Zip_Code__c ='75237');
        
        //insert objects  NOTE: commented out to avoid duplicates
        Insert memphisVan;
        Insert memphisCenter;
        Insert dallasCenter;
        
        //create lists
        List<Vehicle_Schedule__c> vSchedules = new List<Vehicle_Schedule__c>();
        vSchedules.add(new Vehicle_Schedule__c(
        	Distribution_Center__c = memphisCenter.Id,
        	Name = 'Memphis Schedule One',
        	Vehicle__c = memphisVan.Id));
        
        vSchedules.add(new Vehicle_Schedule__c(
        	Distribution_Center__c = dallasCenter.Id,
        	Name = 'Dallas Schedule One'));
        
        //insert lists
        //Insert vSchedules;
        Isr = Database.insert(vSchedules, false);
        
        //iterate through list
        for(Database.SaveResult sr : Isr){
            if(!sr.isSuccess()){
                for(Database.Error err : sr.getErrors()){
                    //log error
                    system.debug(err.getMessage());
                }
            }
        }
    }
}