force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>MAIL-{0000}</displayFormat>
        <label>Mail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/fields/Missing__c.field-meta.xml
<CustomField>
    <fullName>Missing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Missing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MailTriggerHandler.cls
public class MailTriggerHandler {
	
    public static void checkApprovalLock(List<Mail__c> appList){
        
        for(mail__c m : appList){
            
            if(approval.isLocked(m.id)){
                
                m.addError('Record is Locked');
                
            }
            
        }
        
    }
    
    public static void checkDateIfMissing(List<Mail__c> mailList){
        
        for(Mail__c m : mailList){
            
            if(m.missing__c == true && m.CreatedDate.addDays(730) >= Date.today()){
                
                m.AddError('Records must be maintained for missing mail for no less than two years.');
                
            }
            
        }
        
    }
    
}